urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView
from sis.core.views import *
from sis.core.views_parent import *
from sis.core.views_teacher import *
from sis.core.views_admin import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin as aadmin
aadmin.autodiscover()

urlpatterns = patterns('',
     # General
     url(r'^$', home, name='home'),
     #url(r'^index$', home, name='index'),
     url(r'^change_view/(?P<view>.+)$', change_view, name='change_view'),

     url(r'^offered_classes', offered_classes, name='offered_classes'),

     # Parent
     url(r'^enroll_form$', enroll_form, name='enroll_form'),
     url(r'^enroll$', enroll, name='enroll'),
     url(r'^familyinfo$', familyinfo, name='familyinfo'),
     url(r'^users/(?P<uid>.+)/$', user_profile, name='user_profile'),
     url(r'^family_tuition/(?P<fid>.+)$', family_tuition, name='family_tuition'),
     url(r'^edit_student$', edit_student, name='edit_student'),
     url(r'^edit_student/(?P<sid>.+)$', edit_student, name='edit_student'),
     url(r'^student_score/(?P<sid>.+)$', student_score, name='student_score'),
     url(r'^review_tuition_paypal$', review_tuition_paypal, name='review_tuition_paypal'),
     url(r'^review_tuition_check$', review_tuition_check, name='review_tuition_check'),

     # Teacher

     url(r'^grading_policy/(?P<cid>.+)$', grading_policy, name='grading_policy'),
     url(r'^classroaster/(?P<cid>.+)$', classroaster, name='classroaster'),
     url(r'^record/(?P<class_id>.+)$', record, name='record'),
     url(r'^record_attendance/(?P<class_id>.+)$', record_attendance, name='record_attendance'),

     url(r'^record_grade/(?P<cat_id>.+)$', record_grade, name='record_grade'),
     url(r'^add_new_grade/(?P<cat_id>.+)$', add_new_grade, name='add_new_grade'),
     url(r'^edit_grade/(?P<gi_id>.+)$', edit_grade, name='edit_grade'),
     url(r'^del_grade/(?P<gi_id>.+)$', del_grade, name='del_grade'),

     url(r'^prepare_report/(?P<class_id>.+)$', prepare_report, name='prepare_report'),
     url(r'^evaluation_comment/(?P<enrolldetail_id>.+)$', evaluation_comment, name='evaluation_comment'),

     url(r'^accounts/profile', profile, name='profile'),
     #(r'^accounts/', include('sis.registration.urls')),
     #(r'^accounts/', include('sis.registration.backends.default.urls')),
     url(r'^accounts/', include('registration.backends.simple.urls')),
     url(r'^del_attendance/(?P<cs_id>.+)$', del_attendance, name='del_attendance'),
     url(r'^edit_attendance/(?P<cs_id>.+)$', edit_attendance, name='edit_attendance'),

     url(r'^add_new_attendance/(?P<class_id>.+$)', add_new_attendance, name='add_new_attendance' ),

     #url(r'^calculate_total/(?P<class_id>.+)$', calculate_total, name='calculate_total'),
     url(r'^assignments/(?P<cat_id>.+)$', assignments, name='assignments'),
     url(r'^assignment_edit/(?P<aid>.+)$', edit_assignment, name='assignment_edit'),
     url(r'^manage_files/(?P<aid>.+)$', manage_files, name='manage_files'),

     url(r'^del_assignment/(?P<aid>.+)$', del_assignment, name='del_assignment'),
     url(r'^del_all_homework_files/(?P<aid>.+)$', del_all_homework_files, name='del_all_homework_files'),

     url(r'^view_assignments/(?P<cat_id>.+$)', view_assignments, name='view_assignments'),
     url(r'^new_assignment/(?P<class_id>.+$)', new_assignment, name='new_assignment'),
     url(r'^evaluation_comment/(?P<enrolldetail_id>.+$)', evaluation_comment, name='evaluation_comment'),
     url(r'^report_card/(?P<enrolldetail_id>.+$)', report_card, name='report_card'),
     url(r'^notify_report_card/(?P<class_id>.+$)', notify_report_card, name='notify_report_card'),

     # Admin
     url(r'^semester$', semesters, name='semesters'),
     url(r'^edit_semester$', edit_semester, name='edit_semester'),
     url(r'^edit_semester/(?P<sem_id>[0-9]+)$', edit_semester, name='edit_semester'),
     url(r'^semester/(?P<sid>[0-9]+)$', semester, name='semester'),
     url(r'^semesterlist$', semesterlist, name='semesterlist'),
     url(r'^classlist/(?P<sem_id>[0-9]+)$', classlist, name='classlist'),
     url(r'^edit_class/(?P<sem_id>[0-9]+)$', edit_class, name='add_class'),
     url(r'^edit_class/(?P<sem_id>[0-9]+)/(?P<class_id>[0-9]+)$', edit_class, name='edit_class'),
     url(r'^delete_class/(?P<class_id>[0-9]+)$', delete_class, name='delete_class'),
     url(r'^payment$', payment, name='payment'),
     url(r'^class_enrollment$', class_enrollment, name='class_enrollment'),
     url(r'^unpaid_payment$', unpaid_payment, name='unpaid_payment'),
     url(r'^class_enrollment$', class_enrollment, name='class_enrollment'),

     url(r'^3.14159sisadmin', sisadmin, name='sisadmin'),
     url(r'^sisadmincmd/(?P<adminid>.+)/(?P<command>.*)/(?P<subject>.*)$', sisadmin, name='sisadmin'),
     url(r'^active_directory', active_directory, name='active_directory'),
     url(r'^teacher_directory', teacher_directory, name='teacher_directory'),
     url(r'^family_directory/$', ListView.as_view(model=Family ), name='family_directory'),
     # url(r'^sys_config/', system_config, name='sys_config'),
     url(r'^school_info/', school_info, name='school_info'),
     url(r'^new_school_info/', new_school_info, name='new_school_info'),

     url(r'^signup/', signup, name='signup'),

     url(r'^help/', help, name='help'),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(aadmin.site.urls)),


)

core/models.py
import datetime, base64, os, copy
from subprocess import Popen, PIPE
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from operator import attrgetter  # , itemgetter
from phonenumber_field.modelfields import PhoneNumberField
from sis.core.util import id_encode, median, det_encode

this_year = datetime.date.today().year
BIRTH_YEAR_CHOICES = tuple(
  [(str(n), str(n)) for n in range(this_year - 22, this_year - 2)])
SEMESTER_YEAR_CHOICES = tuple(
  [(str(n), str(n)) for n in range(this_year - 1, this_year + 3)])

MONTH_CHOICES = (
  (1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'),
  (7, 'Jul'), (8, 'Aug'),
  (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'))
DAY_CHOICES = tuple([(n, n) for n in range(1, 32)])
SEMESTER_CHOICES = (
  ('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'))
STATE_CHOICES = (('CA', 'CA'), ('CT', 'CT'), ('NY', 'NY'))


class School(models.Model):
  name = models.CharField(max_length=30, verbose_name='School Name')
  domain = models.CharField(max_length=100, primary_key=True)

  chineseName = models.CharField(max_length=30, verbose_name='Chinese Name',
                                 blank=True, default='')
  location = models.TextField(null=True, blank=True)
  mailStop = models.TextField(null=True, blank=True)
  phone = PhoneNumberField(help_text='Home Phone', null=True, blank=True)

  adminEmail = models.EmailField(blank=True, help_text='Principal email')
  deanEmail = models.EmailField(blank=True, help_text='Dean email')
  registrarEmail = models.EmailField(blank=True, help_text='Registrar email')
  treasurerEmail = models.EmailField(blank=True, help_text='Treasurer email')
  policy = models.TextField(null=True, blank=True)
  createDate = models.DateField(auto_now_add=True)
  banner = models.FileField(upload_to='school%y%m%d%H%M%S/', null=True,
                            blank=True)
  logo = models.FileField(upload_to='school%y%m%d%H%M%S/', null=True,
                          blank=True)
  admin = models.ForeignKey(User, null=True)

  def eid(self):
    return id_encode(self.id)

  def det_id(self):
    return det_encode(self.id)

  def __repr__(self):
    return self.name

  def __str__(self):
    return self.name


class Role(models.Model):
  user = models.OneToOneField(User)
  school = models.ForeignKey(School)
  is_admin = models.BooleanField(default=False)
  is_dean = models.BooleanField(default=False)
  is_registrar = models.BooleanField(default=False)
  is_staff1 = models.BooleanField(default=False)
  is_staff2 = models.BooleanField(default=False)


class Semester(models.Model):
  school = models.ForeignKey(School)
  schoolYear = models.CharField(max_length=20, choices=SEMESTER_YEAR_CHOICES)
  semester = models.CharField(max_length=20, choices=SEMESTER_CHOICES)
  # If enrollment is needed. set false to 2nd semester which has not change
  need_enroll = models.BooleanField()
  regStart = models.DateField(null=True, verbose_name='Registration Start Data',
                              help_text='Format: YYYY-MM-DD')
  regEnd = models.DateField(null=True, verbose_name='Registration End Data',
                            help_text='Format: YYYY-MM-DD')
  recordStart = models.DateField(null=True,
                                 verbose_name='Score recording start data',
                                 help_text='Format: YYYY-MM-DD')
  recordEnd = models.DateField(null=True,
                               verbose_name='Score recording end data',
                               help_text='Format: YYYY-MM-DD')
  # The previous semester with same classes
  copyFrom = models.ForeignKey('Semester', null=True, blank=True,
                               related_name="previous",
                               help_text="Copy semester setting from")

  def eid(self):
    return id_encode(self.id)

  def __repr__(self):
    return self.schoolYear + ' ' + self.semester

  def __str__(self):
    return self.schoolYear + ' ' + self.semester

  class Meta:
    unique_together = (('schoolYear', 'semester'))


class Family(models.Model):
  schools = models.ManyToManyField(School)
  user = models.OneToOneField(User, related_name="profile")
  staff_role = models.CharField(max_length=50)
  streetNumber = models.CharField(max_length=50, help_text='Street')
  city = models.CharField(max_length=50, help_text='City')
  state = models.CharField(choices=STATE_CHOICES, max_length=3,
                           help_text='State')
  zipcode = models.CharField(max_length=10, help_text='Zip Code')
  homePhone = PhoneNumberField(help_text='Home Phone')
  mobilePhone = PhoneNumberField(blank=True, help_text='Cell Phone')
  altEmail = models.EmailField(blank=True, help_text='Alt. Email')
  parent1FirstName = models.CharField(max_length=20, help_text='First Name')
  parent1LastName = models.CharField(max_length=20, help_text='Last Name')
  parent1ChineseFullName = models.CharField(blank=True, max_length=20,
                                            help_text='Chinese Name')
  parent2FirstName = models.CharField(blank=True, max_length=20,
                                      help_text='First Name')
  parent2LastName = models.CharField(blank=True, max_length=20,
                                     help_text='Last Name')
  parent2ChineseFullName = models.CharField(blank=True, max_length=20,
                                            help_text='Chinese Name')
  participation = models.CharField(blank=True, max_length=20,
                                   help_text='Participation')
  enroll = models.ManyToManyField('Semester', through='Tuition')

  def cache(self):
    self._cached_copy = copy.deepcopy(vars(self))

  def save(self):
    attrs = []
    if self.id:

      for k, v in vars(self).iteritems():
        if k in ['user_id', 'id'] or k.startswith('_'):
          continue
        try:
          if v == self._cached_copy[k]:
            attrs.append((k, v, None))
          else:
            attrs.append((k, v, self._cached_copy[k]))
        except:
          attrs.append((k, v, self._cached_copy[k]))
    print 'attrs', attrs
    models.Model.save(self)

  def eid(self):
    return id_encode(self.id)

  def teaches(self):
    semester = current_reg_semester(self.school)
    classes = list(Class.objects.filter(Q(semester=semester) & (
      Q(headTeacher=self) | Q(assocTeacher1=self) | Q(assocTeacher2=self))))
    classes.sort(key=attrgetter('name'))
    print 'teaches', semester, classes
    return classes

  def is_parent(self):
    return self.student_set.all()

  def is_teacher(self):
    return self.teaches()

  def is_admin(self):
    return self.user.is_superuser

  def parent1(self):
    return self.parent1FirstName + ' ' + self.parent1LastName

  def parent1_fullname(self):
    return self.parent1FirstName + ' ' + self.parent1LastName + (
      "(" + self.parent1ChineseFullName + ")" if self.parent1ChineseFullName else '')

  def __str__(self):
    return self.parent1FirstName + ' ' + self.parent1LastName

  def parent2(self):
    return self.parent2FirstName + ' ' + self.parent2LastName + (
      "(" + self.parent2ChineseFullName + ")" if self.parent2ChineseFullName else '')

  def address(self):
    return ','.join([self.streetNumber, self.city, self.state, self.zipcode])

  def emails(self):
    if self.altEmail:
      return self.user.email + ',' + self.altEmail
    return self.user.email


ROLE_CHOICES = (
  ('School Admin', 'School Admin'), ('Dean', 'Dean'),
  ('Registrar', 'Registrar'))


class Staff(models.Model):
  family = models.ForeignKey(Family)
  title = models.CharField(max_length=30, verbose_name='Title')

  firstName = models.CharField(max_length=30, verbose_name='First Name')
  lastName = models.CharField(max_length=30, verbose_name='Last Name')
  chineseFullName = models.CharField(max_length=30,
                                     verbose_name='Chinese Full Name',
                                     blank=True, default='')
  bio = models.TextField()
  roles = models.ManyToManyField('Role')


LANG_CHOICES = (
  ('English', 'English'), ('Mandarin', 'Mandarin'), ('Cantonese', 'Cantonese'),
  ('Other', 'Other'))
GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))


class Student(models.Model):
  studentID = models.CharField(max_length=20)
  firstName = models.CharField(max_length=30, verbose_name='First Name')
  lastName = models.CharField(max_length=30, verbose_name='Last Name')
  chineseFullName = models.CharField(max_length=30,
                                     verbose_name='Chinese Full Name',
                                     blank=True, default='')
  birthday = models.DateField(null=True, verbose_name='Birthday',
                              help_text='Format: YYYY-MM-DD')
  homeLanguage = models.CharField(max_length=15, choices=LANG_CHOICES,
                                  verbose_name='Home Language')
  gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
  family = models.ForeignKey(Family)
  enroll = models.ManyToManyField('Class', through='EnrollDetail')

  def eid(self):
    self.cid = id_encode(self.id)
    return self.cid

  def __str__(self):
    return self.firstName + ' ' + self.lastName

  class Meta:
    unique_together = (('firstName', 'birthday', 'family'))


class Class(models.Model):
  name = models.CharField(max_length=200)
  description = models.TextField(default='', null=True, blank=True)
  semester = models.ForeignKey(Semester)
  elective = models.BooleanField(default=False,
                                 help_text="check if this is an elective")
  headTeacher = models.ForeignKey(User, related_name='HeadTeacher', null=True,
                                  blank=True)
  assocTeacher1 = models.ForeignKey(User, related_name='AssocTeacher1',
                                    null=True, blank=True)
  assocTeacher2 = models.ForeignKey(User, related_name='AssocTeacher2',
                                    null=True, blank=True)

templates/assignment_edit.html
{% extends "base.html" %}
{% load core_tags %}


{% block theme %} <link href="{% static_path %}/css/red.css" rel="stylesheet" type="text/css" /> 
<link rel="stylesheet" type="text/css" href="{% static_path %}/css/jquery.cleditor.css" />

<script type="text/javascript" src="{% static_path %}/js/jquery.cleditor.min.js"></script>

{% endblock %}
{% block title %} Assignment  {% endblock %}

{% block content %}
						
<script>
    $(function() {
        $( "#assign_date" ).datepicker();
        $( "#due_date" ).datepicker();
        $( "#due_date" ).datepicker( "option", "dateFormat", "mm-dd-yy" ).val("{{gi.duedate|date:"m-d-Y"}}");
	 $("#Description").cleditor();	
    });
</script>
<div class="teacher">
    <h3 class="title"> Homework for Class: {{gi.category.classPtr.name}} </h3>


    <h3> Edit Assignment </h3> 
    <form class="red" action='{% url 'assignment_edit' aid=gi.eid %}' method='post'>
        <label> Name: </label> <input type='text' name='Name'  value="{{gi.name}}" disabled="disabled"/> change not allowed <br/>
        {# <label> Assign Date </label> {{assignment_date}}  <br/> #}
        <label> Due Date: </label> {{due_date}}  <br/>

        <label> Description: </label><br />
        <div style="margin-left: 30px;"><textarea id="Description" name='Description'
          rows=0 cols=0>{{gi.assignmentDescr}}</textarea><br/>
         </div>
        {% csrf_token %}

        {% csrf_token %}
        <input class="button" type="submit" name="Update" value="Update" />
        <input class="button" type="submit" name="Delete" value="Delete this Homework" />
    </form>
    <a class="button" href='{% url 'del_all_homework_files' aid=gi.eid %}'> Delete all uploaded files (use carefully) </a> 
</div>
{% endblock %}

templates/assignments.html
{% extends "base.html" %}
{% load core_tags %}

{% block theme %} 

<link href="{% static_path %}/css/red.css" rel="stylesheet" type="text/css" /> 
<link rel="stylesheet" type="text/css" href="{% static_path %}/css/jquery.cleditor.css" />
<link href="{% static_path %}/css/record_attendance.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="{% static_path %}/js/jquery.cleditor.min.js"></script>

{% endblock %}

{% block title %} Assignments  {% endblock %}

{% block content %}
<script>
    $(function() {
        $( "#due_date" ).datepicker();
        $( "#due_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
	
	 $("#Description").cleditor();	
    });
</script>
<div class="teacher">
    <div style="padding: 5px;">
    <h3 class="inCenter"> Assignments for Class {{category.classPtr.name}} </h3>

    {% if gditems %}
    <div class="record-tab">
	<div class="accordion" id="assignment">
	   <div class="accordion-group">
                        <div class="accordion-heading">
	   			<div class="row-fluid">
					<div class="span4" style="padding-left: 15px;"><h5>Name </h5></div>
					<div class="span4"><h5>Due Date  </h5></div>
	   			</div>
			</div>
	  </div> 
	   {% for gditem in gditems %}
  		<div class="accordion-group">
    			<div class="accordion-heading">
          		  <div class="row-fluid">
      			     <div class="span4">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#assignment" 
					href="#{{gditem.eid}}" style="text-decoration:underline;">
  					{{gditem.name}}<i class="icon-caret-down" style="margin: 3px; text-decoration:none;"></i>	
      			        </a>
			     </div>
      			     <div class="span4" style="padding-top: 5px;" >{{gditem.duedate| date:'m-d-Y'}}</div>
			     <div class="span4" style="padding-top: 5px;">
				<a href="{{gditem.download_url}}"  target="_blank" >
					<button class="btn btn-small btn-info" type="button">Upload Files</button></a> 
			        <a href="{% url 'assignment_edit' aid=gditem.cid %}" > 
					 <button class="btn btn-small btn-warning" type="button">Edit</button></a> 
				<button class="btn btn-small btn-danger" type="button" data-toggle="modal" data-target="#deleteModal">Delete</button>
			       {# <a href="{% url 'manage_files' aid=gditem.cid %}" > <button class="btn btn-small btn-warning" type="button">Manage Files</button></a> #}

			    </div>
    		    	 </div>
			</div>
    			<div id="{{gditem.cid}}" class="accordion-body collapse">
      			  <div class="accordion-inner well"><span class="label label-info">Homework Description:</span>
        			<p>{{gditem.assignmentDescr|safe}} </p>
      			  </div>
    			</div>
  		</div>
		<!-- modal --!>
		<div id="deleteModal" class="modal hide fade" style="position: relative; top: auto; left: auto; margin: 0 auto 20px;"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-body">
              			<h4>Are you sure?</h4>			
			</div>
			<div class="modal-footer">
              			<button class="btn" data-dismiss="modal">No</button>
              			<a href="{% url 'del_assignment' aid=gditem.cid %}" ><button class="btn btn-primary">Continue to Delete</button></a>
            		</div>
          	</div>
	  {% endfor %}
	</div>
    </div>
    {% endif %}

    <div class="well">
    <h3 class="inCenter"> New Assignment </h3> 
    <form class="red" action='{% url 'assignments' cat_id=category.eid %}' method='post'>
        <label> Name: </label> <input type='text' name='Name'  value="{{category.name}} {{category.serial}}"/>  <br/>
        {# <label> Assign Date </label> {{assignment_date}}  <br/> #}
        <label> Due Date: </label> {{due_date}}  <br/>

        <label> Description: </label><br /><div style="margin-left: 30px;">
        <textarea id="Description" name='Description' value="{{category.assignmentDescr}}"></textarea><br/>
         </div>
        {% csrf_token %}
        <div style="margin-left: 30px;"><input class="button" type="submit" name="Update" value="Update" /></div>
    </form>
    </div>
  </div>       
</div>
{% endblock %}

templates/edit_student.html
{% extends "base.html" %}
{% load core_tags %}

{% block theme %} <link href="{% static_path %}/css/green.css" rel="stylesheet" type="text/css" /> {% endblock %}
{% block title %} Student {% endblock %}

{% block content %}
<script>
    $(function() {
        $( "#id_birthday" ).datepicker();
        $( "#id_birthday" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    });
</script>

<div class="parent">
    <h2 class="title">Student Information</h2>
    <form class="signform" action="/edit_student{% if student.id %}/{{student.eid}}{% endif %}" method="POST"> 
	<div><label> First Name:* </label>  {{form.firstName}} 
        {% if form.firstName.errors%}{{form.errors.firstName}}{% endif %} </div>
        <div><label > Last Name:* </label>  {{form.lastName}}  
        {% if form.lastName.errors%}{{form.errors.lastName}}{% endif %} </div>
        <div> <label>Chinese Full Name: </label>  {{form.chineseFullName}} </div> 
        <div><label> Birthday:* </label> {{form.birthday}} 
        {% if form.birthday.errors%}<br/><br/>{{form.errors.birthday}}{% endif %} </div>
        <div><label> Main Language:* </label>  {{form.homeLanguage}}  
        {% if form.homeLanguage.errors%}<br/><br/>{{form.errors.homeLanguage}}{% endif %} </div>
        <div><label > Gender:* </label>  {{form.gender}}  
        {% if form.gender.errors%}<br/><br/>{{form.errors.gender}}{% endif %} </div>
        {{ form.non_field_errors }}
        {% csrf_token %}
	<br/>
	<div class="inCenter">
        {% if student %}
        <button class="btn btn-medium btn-green" type="submit" name="Update">Update Student Info </button> 
        {% else %}
        <button class="btn btn-medium btn-green" type="submit" name="Add Student">Add Student </button> 
        {% endif %}
	</div>
    </form> 
    <br/>
</div>

{% endblock %}

templates/editsemester.html
{% extends 'base.html' %} 
{% load core_tags %}

{% block theme %} <link href="{% static_path %}/css/blue.css" rel="stylesheet" type="text/css" /> {% endblock %}
{% block title %}  Semester Setup {% endblock %}
{% block content %} 
<script>
    $(function() {
        var regStart = $("#id_regStart").val();
        $( "#id_regStart" ).datepicker();
        $( "#id_regStart" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
        $( "#id_regStart").width(100);
        $( "#id_regStart").val(regStart);
        var regEnd = $("#id_regEnd").val();
        $( "#id_regEnd" ).datepicker();
        $( "#id_regEnd" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
        $( "#id_regEnd").width(100);
        $( "#id_regEnd").val(regEnd);

        var recordStart = $("#id_recordStart").val();
        $( "#id_recordStart" ).datepicker();
        $( "#id_recordStart" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
        $( "#id_recordStart").width(100);
        $( "#id_recordStart").val(recordStart);

        var recordEnd = $("#id_recordEnd").val();
        $( "#id_recordEnd" ).datepicker();
        $( "#id_recordEnd" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
        $( "#id_recordEnd").width(100);
        $( "#id_recordEnd").val(recordEnd);


    });
</script>
<div class="admin2"
    <br/>
    <form method='post' action='/edit_semester{%if sem %}/{{sem.eid}}{% endif %}'> 
        <p> <label> School Year </label>: {{ sform.schoolYear }} </p> 
        <p> <label> Semester </label>: {{ sform.semester }} </p> 
        <p> <label> Copy from </label>: {{ sform.copyFrom }} </p> 
        <p> <label> Registration start </label>: {{ sform.regStart }} </p> 
        <p> <label> Registration end </label>: {{ sform.regEnd }} </p> 
        <p> <label> Record start </label>: {{ sform.recordStart }} </p> 
        <p> <label> Record end </label>: {{ sform.recordEnd }} </p> 
        <p> <label> Enroll required</label>: {{ sform.need_enroll }} </p> 

        {# {{ sform.as_p }} #}
        {% csrf_token %}
        <input class="btn btn-success" type="submit" name="Add Semester" value="     Update     " />


    </form> 
</div>
{% endblock %} 

templates/error.html
{% extends "base.html" %}
{% load core_tags %}

{% block theme %} <link href="/css/red.css" rel="stylesheet" type="text/css" /> {% endblock %}
{% block title %} Error  {% endblock %}

{% block content %}
{% endblock %}

templates/manage_files.html
{% extends "base.html" %}
{% load core_tags %}


{% block theme %} <link href="{% static_path %}/css/red.css" rel="stylesheet" type="text/css" /> 
<link rel="stylesheet" type="text/css" href="{% static_path %}/css/jquery.cleditor.css" />

<script type="text/javascript" src="{% static_path %}/js/jquery.cleditor.min.js"></script>

{% endblock %}
{% block title %} Assignment  {% endblock %}

{% block content %}
						
<div class="teacher">
    <h3 class="title"> Homework Files for Class: {{gi.category.classPtr.name}} </h3>

    <form class="red" action='' method='post'>
	 {% for file in files %}
	 {{file}}
	 {% endfor %}
        {% csrf_token %}
        <input class="button" type="submit" name="Update" value="Update" />
    </form>
</div>
{% endblock %}